# 1.06
# Command to build and tag/name: docker build -t docker-clock . 
# Command to run container and clock: docker run docker-clock

# The base image:
FROM devopsdockeruh/overwrite_cmd_exercise

# This will be executed when using "docker run"
CMD ["/bin/bash"]
CMD [" -c"]
